pairs = [
    (["hello","hi","hey","hey there","is anyone there?","good day", "whats up","greetings"], ["Hi there, how can I help?","Hi there!", "Hello!"]),
    (["i am Leaving", "have a Good day","bye","goodbye","c ya","cya","see you later","see ya"], ["Sad to see you go :(", "Talk to you later","Goodbye!", "See you later!"]),
    (["how are you","how are u","how do you do","how are you?","how are u?","how do you do?"],["I'm fine Thank you!","I'm fine Thanks!","I'm fine, and you?"]),
    (["what is your name", "what should i call you","what is your name?", "what should i call you?"],["My name is EasyTalker and I'm a chatbot."]),
    (["i'm fine thank you","i am fine thank you"],["I'm glad to hear that","I'm glad"]),
    (["what is progamming?", "what is coding?", "tell me about programming", "tell me about coding", "what is software development?"],["Programming, coding or software development, means writing computer code to automate tasks."]),
    (["where can I learn to code?", "best way to learn to code", "how can I learn programming", "good programming resources", "can you recommend good coding resources?"],["Check out the NeuralNine YouTube channel and The Python Bible series (7 in 1)."]),
    (["what can you do","what can you do?"],["I can chat with you","I can talk with you for a while","You can ask me about programming"]),
    (["i had an accident","i was in a fight"],["I'm sorry to hear that","Please make sure to seek medical attention"]),
    (["i graduated","i won an award","i won a competetion","i got a job"],["Congrats!","Congratulations!"]),
    (["thanks","thank you","that's helpful","awesome, thanks","thanks for helping me"],["Happy to help!","Any time!","My pleasure"]),
    (["tell me a joke","joke","make me laugh"],["A perfectionist walked into a bar...apparently, the bar wasn't set high enough",
        "I ate a clock yesterday, it was very time-consuming",
        "Never criticize someone until you've walked a mile in their shoes. That way, when you criticize them, they won't be able to hear you from that far away. Plus, you'll have their shoes.",
        "The world tongue-twister champion just got arrested. I hear they're gonna give him a really tough sentence.",
        "I own the world's worst thesaurus. Not only is it awful, it's awful.",
        "What did the traffic light say to the car? \"Don't look now, I'm changing.\"",
        "What do you call a snowman with a suntan? A puddle.",
        "How does a penguin build a house? Igloos it together",
        "I went to see the doctor about my short-term memory problems - the first thing he did was make me pay in advance",
        "As I get older and I remember all the people I've lost along the way, I think to myself, maybe a career as a tour guide wasn't for me.",
        "o what if I don't know what 'Armageddon' means? It's not the end of the world.",
        "Why don't skeletons fight each other?\nBecause they don't have the guts!",
        "Why did the scarecrow win an award?\nBecause he was outstanding in his field!"]),
    (["haha","lol","thats funny"],["Glad I could make you laugh !"]),
    (["who made you","who designed you","who programmed you"],["I was made by Abdelrahman Mohamed"]),
    (["who is he","who is that","who is abdelrahman","abdelrahman mohamed"],["Head over to any of his social profiles to find out! \nLinkedin: https://www.linkedin.com/in/abdelrahman-mohamed-a1956b247/ \nGithub: https://github.com/Abdelrahman822000"]),
    (["contact developer","contact Abdelrahman","contact programmer","contact creator","how can i contact Abdelrahman","how can i contact creator","how can i contact programmer","how can i contact developer"],["You can contact my creator at his Linkedin profile : https://www.linkedin.com/in/abdelrahman-mohamed-a1956b247/"]),
    (["i am good","I'm good","i am fine"," i'm fine","good"],["Good to know!"]),
    (["you are useless","useless","suggest","suggestions","you are bad"],["Please mail your suggestions to a.mohamed822000@gmail.com .\nThank you for helping me improve!"]),
    (["tell me a riddle","riddle"],["What two things can you never eat for breakfast?.....Lunch and Dinner!",
        "What word is spelled incorrectly in every single dictionary?.....Incorrectly",
        "How do you make the number one disappear?.....Add the letter G and it's 'gone'!",
        " What will you actually find at the end of every rainbow?.....The letter 'w'",
        "What can be caught but never thrown?.....A cold!",
        "What has a thumb and four fingers but is not actually alive?.....Your Gloves!",
        " What 5-letter word becomes shorter when you add two letters to it?.....Short",
        "Why can't a bike stand on it's own?.....It is two-tired."]),
    (["how old are you","when were you made","what is your age"],["I was made in 2024"])
]